### ISSUE TITLE
Crash on pressing the windows key

### ISSUE THREAD

**Issue by kriticalflare** [Mithil467/mitype#1]
Got the project running on windows with your instructions , pressing the windows key during the typing test causes it to crash.

Platform: Windows 10
Version: Clone from master @ commit https://github.com/Mithil467/mitype/commit/d14b810f56d75b4f622aa35da7745be263c4d22d
Stacktrace:
``` (Venv) F:\PythonProjects\mitype\mitype>python local_test.py
Traceback (most recent call last):
  File "local_test.py", line 5, in <module>
    obj.start()
  File "F:\PythonProjects\mitype\mitype\app.py", line 192, in start
    curses.wrapper(self.main)
  File "C:\Users\Kriticalflare\AppData\Local\Programs\Python\Python38-32\lib\curses\__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "F:\PythonProjects\mitype\mitype\app.py", line 169, in main
    self.KeyPrinter(win, key)
  File "F:\PythonProjects\mitype\mitype\app.py", line 107, in KeyPrinter
    win.addstr(self.LineCount, 0, self.CurrentWord)
ValueError: embedded null character
```

**Comment by Mithil467** [comment]
Thanks for letting me know about the issue. Confirm this bug exists in https://github.com/Mithil467/mitype/commit/46841dbc92fb10a73c934f351de121e23ea6dffc. Will try to fix it in upcoming commits :+1:
